name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Mnaual Trigger"
        default: "MT"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python -m pytest --cov=owm --cov-report=xml tests/ -vv
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=jay-lee-lge 
            -Dsonar.projectKey=jay-lee-lge_lg24devsecops 
            -Dsonar.sources=owm/
            -Dsonar.tests=tests/
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pyre Action
        uses: facebook/pyre-action@v0.0.1
        with:
          repo-directory: './'
          requirements-path: './requirements.txt'